// Map-N data manager v1.0.0
// Import/export/clear are scoped to the current chat. Rollback rebuilds derived state from the live chat.

const dmWait=ms=>new Promise(r=>setTimeout(r,ms));
const DM_VERSION=1;
const DM_DEBUG_SUFFIX=':debug-v1';
const DM_SNAPSHOT_SUFFIX=':timeline-v1';

function dmKeys(inst){return{main:inst.memoryKey,scene:`${inst.memoryKey}:scene-v2`,presence:`${inst.memoryKey}:presence-v1`,debug:`${inst.memoryKey}${DM_DEBUG_SUFFIX}`,timeline:`${inst.memoryKey}${DM_SNAPSHOT_SUFFIX}`};}
function dmRead(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}
function dmWrite(k,v){if(v===null||v===undefined)localStorage.removeItem(k);else localStorage.setItem(k,JSON.stringify(v));}
function dmHash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function dmChatSignature(inst){const chat=inst.ctx?.chat||[];return chat.map((m,i)=>`${i}:${m?.is_user?'u':'a'}:${dmHash(String(m?.mes||''))}`).join('|');}
function dmDebugState(inst){const k=dmKeys(inst).debug;return dmRead(k)||{enabled:false,logs:[]};}
function dmSaveDebug(inst,d){dmWrite(dmKeys(inst).debug,d)}
function dmLog(inst,type,data={}){const d=dmDebugState(inst);if(!d.enabled)return;d.logs.push({time:new Date().toISOString(),type,...data});if(d.logs.length>300)d.logs=d.logs.slice(-300);dmSaveDebug(inst,d);console.debug('[Map-N debug]',type,data)}
function dmClearDerived(inst,{keepDebug=true}={}){const k=dmKeys(inst);localStorage.removeItem(k.main);localStorage.removeItem(k.scene);localStorage.removeItem(k.presence);localStorage.removeItem(k.timeline);if(!keepDebug)localStorage.removeItem(k.debug);inst.path=['世界舆图'];inst.discovered=new Set(['世界舆图']);inst.encountered=new Set();inst.currentPos=null;inst.currentChars=[];inst.__mapNSceneStore={version:2,learnedLocations:{},knownCharacters:{}};inst.__mapNPresenceState={current:[],lastLocation:null};}
async function dmRebuild(inst,reason='manual'){
 const debug=dmDebugState(inst);dmClearDerived(inst,{keepDebug:true});inst.memoryKey=inst.scopeKey();
 try{await inst.prime(true)}catch(e){dmLog(inst,'rebuild-prime-error',{message:String(e)})}
 const chat=inst.ctx?.chat||[];for(let i=0;i<chat.length;i++){const m=chat[i];if(m?.mes)inst.process(String(m.mes),!!m.is_user)}
 const snap={version:DM_VERSION,signature:dmChatSignature(inst),chatLength:chat.length,rebuiltAt:Date.now()};dmWrite(dmKeys(inst).timeline,snap);dmWrite(dmKeys(inst).debug,debug);inst.save();inst.render();dmLog(inst,'rebuild',{reason,chatLength:chat.length,currentPos:inst.currentPos,currentChars:[...(inst.currentChars||[])]});return snap;
}
function dmExport(inst){const k=dmKeys(inst);const payload={format:'Map-N',version:DM_VERSION,exportedAt:new Date().toISOString(),scope:inst.memoryKey,data:{main:dmRead(k.main),scene:dmRead(k.scene),presence:dmRead(k.presence)}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Map-N-${Date.now()}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);dmLog(inst,'export',{});}
function dmImport(inst,file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=async()=>{try{const p=JSON.parse(String(r.result||''));if(p?.format!=='Map-N'||!p.data)throw new Error('不是有效的 Map-N 数据文件');const k=dmKeys(inst);dmWrite(k.main,p.data.main);dmWrite(k.scene,p.data.scene);dmWrite(k.presence,p.data.presence);inst.load();inst.__mapNSceneStore=p.data.scene||{version:2,learnedLocations:{},knownCharacters:{}};inst.__mapNPresenceState=p.data.presence||{current:[],lastLocation:null};await inst.prime(true);inst.render();dmWrite(k.timeline,{version:DM_VERSION,signature:dmChatSignature(inst),chatLength:(inst.ctx?.chat||[]).length,importedAt:Date.now()});dmLog(inst,'import',{});resolve()}catch(e){reject(e)}};r.onerror=()=>reject(r.error||new Error('读取文件失败'));r.readAsText(file,'utf-8')})}
function dmMakePanel(inst){if(document.querySelector('#mapN-data-panel'))return;const p=document.createElement('div');p.id='mapN-data-panel';p.style.cssText='position:fixed;right:10px;bottom:12px;z-index:100001;background:#111821;border:1px solid #30363d;border-radius:10px;padding:8px;display:none;gap:6px;flex-wrap:wrap;max-width:280px;color:#c9d1d9;font-size:12px;box-shadow:0 5px 24px rgba(0,0,0,.55)';
 const mk=(t,fn)=>{const b=document.createElement('button');b.textContent=t;b.style.cssText='background:#1c2333;color:#c9d1d9;border:1px solid #30363d;border-radius:6px;padding:6px 8px;font-size:12px';b.onclick=fn;p.appendChild(b);return b};
 mk('导出',()=>dmExport(inst));mk('导入',()=>{const f=document.createElement('input');f.type='file';f.accept='.json,application/json';f.onchange=async()=>{if(!f.files?.[0])return;try{await dmImport(inst,f.files[0]);alert('Map-N：导入完成')}catch(e){alert(`Map-N：导入失败\n${e.message||e}`)}};f.click()});mk('清空',async()=>{if(!confirm('只清空当前聊天的 Map-N 数据？此操作不会影响其他聊天。'))return;dmClearDerived(inst,{keepDebug:true});await dmRebuild(inst,'clear-and-rescan');alert('Map-N：当前聊天数据已清空并按现有对话重建')});mk('回溯',async()=>{await dmRebuild(inst,'manual-rollback');alert('Map-N：已按当前对话重新回溯同步')});
 const dbg=mk('调试：关',()=>{const d=dmDebugState(inst);d.enabled=!d.enabled;dmSaveDebug(inst,d);dbg.textContent=`调试：${d.enabled?'开':'关'}`;dmLog(inst,'debug-toggle',{enabled:d.enabled})});dbg.textContent=`调试：${dmDebugState(inst).enabled?'开':'关'}`;
 mk('复制日志',async()=>{const d=dmDebugState(inst);const text=JSON.stringify(d.logs||[],null,2);try{await navigator.clipboard.writeText(text);alert('Map-N：调试日志已复制')}catch{prompt('复制下面的调试日志：',text)}});document.body.appendChild(p);inst.__mapNDataPanel=p;
 const tools=inst.container?.querySelector('.mapN-tools');if(tools){const b=document.createElement('button');b.type='button';b.title='数据与调试';b.textContent='⚙';b.onclick=()=>{p.style.display=p.style.display==='flex'?'none':'flex'};tools.appendChild(b)}
}
function dmInstallRollbackWatch(inst){const es=inst.ctx?.eventSource,et=inst.ctx?.eventTypes||inst.ctx?.event_types;if(!es||!et)return;let busy=false;const check=async(reason)=>{if(busy)return;const old=dmRead(dmKeys(inst).timeline),sig=dmChatSignature(inst),len=(inst.ctx?.chat||[]).length;if(!old){dmWrite(dmKeys(inst).timeline,{version:DM_VERSION,signature:sig,chatLength:len});return}if(old.signature!==sig){busy=true;dmLog(inst,'timeline-change',{reason,oldLength:old.chatLength,newLength:len});try{await dmRebuild(inst,reason)}finally{busy=false}}};['MESSAGE_SWIPED','MESSAGE_UPDATED','MESSAGE_DELETED','CHAT_CHANGED'].forEach(k=>{if(et[k])es.on(et[k],()=>setTimeout(()=>check(k),80))});const prev=inst.process.bind(inst);inst.process=function(text,isUser=false){prev(text,isUser);setTimeout(()=>{const sig=dmChatSignature(this),len=(this.ctx?.chat||[]).length;dmWrite(dmKeys(this).timeline,{version:DM_VERSION,signature:sig,chatLength:len,updatedAt:Date.now()});dmLog(this,'process',{isUser,currentPos:this.currentPos,currentChars:[...(this.currentChars||[])]})},0)}
async function installDataManager(){for(let i=0;i<120&&!window.MapNInstance;i++)await dmWait(100);const inst=window.MapNInstance;if(!inst||inst.__mapNDataManager)return;inst.__mapNDataManager=true;dmMakePanel(inst);dmInstallRollbackWatch(inst);const k=dmKeys(inst);if(!dmRead(k.timeline))dmWrite(k.timeline,{version:DM_VERSION,signature:dmChatSignature(inst),chatLength:(inst.ctx?.chat||[]).length});console.log('[Map-N] data manager v1.0.0 installed')}
installDataManager();
