// Map-N data manager v1.0.5
// Current-chat import/export/clear + deterministic rollback rebuild + optional debug log.

const dmWait=ms=>new Promise(r=>setTimeout(r,ms));
const DM_VERSION=1,DM_DEBUG_SUFFIX=':debug-v1',DM_SNAPSHOT_SUFFIX=':timeline-v1';
function dmKeys(inst){return{main:inst.memoryKey,scene:`${inst.memoryKey}:scene-v2`,presence:`${inst.memoryKey}:presence-v1`,debug:`${inst.memoryKey}${DM_DEBUG_SUFFIX}`,timeline:`${inst.memoryKey}${DM_SNAPSHOT_SUFFIX}`};}
function dmRead(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}
function dmWrite(k,v){if(v==null)localStorage.removeItem(k);else localStorage.setItem(k,JSON.stringify(v));}
function dmHash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function dmChatSignature(inst){return(inst.ctx?.chat||[]).map((m,i)=>`${i}:${m?.is_user?'u':'a'}:${dmHash(String(m?.mes||''))}`).join('|')}
function dmDebugState(inst){return dmRead(dmKeys(inst).debug)||{enabled:false,logs:[]}}
function dmSaveDebug(inst,d){dmWrite(dmKeys(inst).debug,d)}
function dmLog(inst,type,data={}){const d=dmDebugState(inst);if(!d.enabled)return;d.logs.push({time:new Date().toISOString(),type,...data});if(d.logs.length>300)d.logs=d.logs.slice(-300);dmSaveDebug(inst,d);console.debug('[Map-N debug]',type,data)}
function dmResetRuntime(inst){inst.root={id:'世界舆图',children:[],parent:null};inst.nodeMap={};inst.alias=new Map();inst.entries=[];inst.lastSig='';inst.path=['世界舆图'];inst.discovered=new Set(['世界舆图']);inst.encountered=new Set();inst.currentPos=null;inst.currentChars=[];inst.__mapNSceneStore={version:2,learnedLocations:{},knownCharacters:{}};inst.__mapNPresenceState={current:[],lastLocation:null};}
function dmClearStored(inst,{keepDebug=true,keepTimeline=false}={}){const k=dmKeys(inst);[k.main,k.scene,k.presence].forEach(x=>localStorage.removeItem(x));if(!keepTimeline)localStorage.removeItem(k.timeline);if(!keepDebug)localStorage.removeItem(k.debug)}
function dmClearCurrent(inst){dmClearStored(inst,{keepDebug:true,keepTimeline:false});dmResetRuntime(inst);inst.render();dmLog(inst,'clear',{scope:inst.memoryKey})}
async function dmRebuild(inst,reason='manual'){
 const debug=dmDebugState(inst);dmClearStored(inst,{keepDebug:true,keepTimeline:true});dmResetRuntime(inst);inst.memoryKey=inst.scopeKey();
 try{await inst.prime(true)}catch(e){dmLog(inst,'rebuild-prime-error',{message:String(e)})}
 const chat=inst.ctx?.chat||[];for(let i=0;i<chat.length;i++){const m=chat[i];if(m?.mes)inst.process(String(m.mes),!!m.is_user)}
 const snap={version:DM_VERSION,signature:dmChatSignature(inst),chatLength:chat.length,rebuiltAt:Date.now()};dmWrite(dmKeys(inst).timeline,snap);dmWrite(dmKeys(inst).debug,debug);inst.save();inst.render();dmLog(inst,'rebuild',{reason,chatLength:chat.length,currentPos:inst.currentPos,currentChars:[...(inst.currentChars||[])]});return snap;
}
function dmExport(inst){const k=dmKeys(inst),payload={format:'Map-N',version:DM_VERSION,exportedAt:new Date().toISOString(),scope:inst.memoryKey,data:{main:dmRead(k.main),scene:dmRead(k.scene),presence:dmRead(k.presence)}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Map-N-${Date.now()}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);dmLog(inst,'export',{})}
function dmImport(inst,file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=async()=>{try{const p=JSON.parse(String(r.result||''));if(p?.format!=='Map-N'||!p.data)throw new Error('不是有效的 Map-N 数据文件');dmClearStored(inst,{keepDebug:true,keepTimeline:false});dmResetRuntime(inst);const k=dmKeys(inst);dmWrite(k.main,p.data.main);dmWrite(k.scene,p.data.scene);dmWrite(k.presence,p.data.presence);inst.load();inst.__mapNSceneStore=p.data.scene||{version:2,learnedLocations:{},knownCharacters:{}};inst.__mapNPresenceState=p.data.presence||{current:[],lastLocation:null};await inst.prime(true);inst.render();dmWrite(k.timeline,{version:DM_VERSION,signature:dmChatSignature(inst),chatLength:(inst.ctx?.chat||[]).length,importedAt:Date.now()});dmLog(inst,'import',{sourceScope:p.scope||null});resolve()}catch(e){reject(e)}};r.onerror=()=>reject(r.error||new Error('读取文件失败'));r.readAsText(file,'utf-8')})}
function dmMakePanel(inst){if(document.querySelector('#mapN-data-panel'))return;const p=document.createElement('div');p.id='mapN-data-panel';p.style.cssText='position:absolute;right:58px;top:auto;bottom:112px;z-index:20;background:#111821;border:1px solid #30363d;border-radius:10px;padding:8px;display:none;gap:6px;flex-wrap:wrap;width:min(230px,calc(100% - 86px));max-height:calc(100% - 180px);overflow:auto;color:#c9d1d9;font-size:12px;box-shadow:0 5px 24px rgba(0,0,0,.65);box-sizing:border-box';const mk=(t,fn)=>{const b=document.createElement('button');b.textContent=t;b.style.cssText='background:#1c2333;color:#c9d1d9;border:1px solid #30363d;border-radius:6px;padding:7px 8px;font-size:12px;flex:1 1 82px';b.onclick=fn;p.appendChild(b);return b};
 mk('导出',()=>dmExport(inst));mk('导入',()=>{const f=document.createElement('input');f.type='file';f.accept='.json,application/json';f.onchange=async()=>{if(!f.files?.[0])return;try{await dmImport(inst,f.files[0]);alert('Map-N：导入完成')}catch(e){alert(`Map-N：导入失败\n${e.message||e}`)}};f.click()});mk('清空',()=>{if(!confirm('只清空当前聊天的 Map-N 数据？此操作不会影响其他聊天。'))return;dmClearCurrent(inst);alert('Map-N：当前聊天地图数据已清空')});mk('回溯',async()=>{await dmRebuild(inst,'manual-rollback');alert('Map-N：已按当前对话重新回溯同步')});const dbg=mk('调试：关',()=>{const d=dmDebugState(inst);d.enabled=!d.enabled;dmSaveDebug(inst,d);dbg.textContent=`调试：${d.enabled?'开':'关'}`;dmLog(inst,'debug-toggle',{enabled:d.enabled})});dbg.textContent=`调试：${dmDebugState(inst).enabled?'开':'关'}`;mk('复制日志',async()=>{const text=JSON.stringify(dmDebugState(inst).logs||[],null,2);try{await navigator.clipboard.writeText(text);alert('Map-N：调试日志已复制')}catch{prompt('复制下面的调试日志：',text)}});
 (inst.container||document.body).appendChild(p);inst.__mapNDataPanel=p;const tools=inst.container?.querySelector('.mapN-tools');if(tools){const b=document.createElement('button');b.type='button';b.id='mapN-data-btn';b.title='数据与调试';b.textContent='⚙';b.onclick=e=>{e.stopPropagation();p.style.display=p.style.display==='flex'?'none':'flex'};tools.appendChild(b)}
}
function dmInstallRollbackWatch(inst){const es=inst.ctx?.eventSource,et=inst.ctx?.eventTypes||inst.ctx?.event_types;if(!es||!et)return;let busy=false,suppressSnapshot=false;const check=async(reason)=>{if(busy)return;const old=dmRead(dmKeys(inst).timeline),sig=dmChatSignature(inst),len=(inst.ctx?.chat||[]).length;if(!old){dmWrite(dmKeys(inst).timeline,{version:DM_VERSION,signature:sig,chatLength:len});return}if(old.signature!==sig){busy=true;suppressSnapshot=true;dmLog(inst,'timeline-change',{reason,oldLength:old.chatLength,newLength:len});try{await dmRebuild(inst,reason)}finally{suppressSnapshot=false;busy=false}}};['MESSAGE_SWIPED','MESSAGE_UPDATED','MESSAGE_DELETED'].forEach(k=>{if(et[k])es.on(et[k],()=>setTimeout(()=>check(k),120))});if(et.CHAT_CHANGED)es.on(et.CHAT_CHANGED,()=>setTimeout(()=>{inst.memoryKey=inst.scopeKey();const old=dmRead(dmKeys(inst).timeline);if(!old)dmWrite(dmKeys(inst).timeline,{version:DM_VERSION,signature:dmChatSignature(inst),chatLength:(inst.ctx?.chat||[]).length});dmLog(inst,'chat-change',{scope:inst.memoryKey})},180));const prev=inst.process.bind(inst);inst.process=function(text,isUser=false){prev(text,isUser);if(suppressSnapshot)return;setTimeout(()=>{if(suppressSnapshot)return;const sig=dmChatSignature(this),len=(this.ctx?.chat||[]).length;dmWrite(dmKeys(this).timeline,{version:DM_VERSION,signature:sig,chatLength:len,updatedAt:Date.now()});dmLog(this,'process',{isUser,currentPos:this.currentPos,currentChars:[...(this.currentChars||[])]})},0)}}
async function installDataManager(){for(let i=0;i<120&&!window.MapNInstance;i++)await dmWait(100);const inst=window.MapNInstance;if(!inst||inst.__mapNDataManager)return;inst.__mapNDataManager=true;dmMakePanel(inst);dmInstallRollbackWatch(inst);const k=dmKeys(inst);if(!dmRead(k.timeline))dmWrite(dmKeys(inst).timeline,{version:DM_VERSION,signature:dmChatSignature(inst),chatLength:(inst.ctx?.chat||[]).length});console.log('[Map-N] data manager v1.0.5 installed')}
installDataManager();
