// Map-N entity core v2.0.0
// Single source of truth for location canonicalization, hierarchy scoring and conservative person parsing.
const TIME_PREFIX_RE=/^\s*(?:(?:\d{1,6}年\d{1,2}月\d{1,2}日)|(?:\d{4}[-/.]\d{1,2}[-/.]\d{1,2})|(?:\d{1,2}月\d{1,2}日))?(?:\s*(?:周[一二三四五六日天]|星期[一二三四五六日天]))?(?:\s*(?:上午|下午|晚上|夜间|凌晨|清晨|早上|中午|傍晚))?(?:\s*\d{1,2}:\d{2}(?::\d{2})?)?\s*[|｜]\s*/u;
const BARE_TIME_PREFIX_RE=/^\s*\d{1,2}:\d{2}(?::\d{2})?\s*[|｜]\s*/u;
const CONTAINER_SUFFIX_RE=/(?:国|州|郡|府|县|城|镇|村|寨|庄|岛|海|湾|湖|河|江|山|岭|峪|谷|峡|沟|原|林|泽)$/u;
const ROUTE_SUFFIX_RE=/(?:谷道|山道|官道|古道|栈道|小道|道路|路|径)$/u;
const LOCAL_DETAIL_SUFFIX_RE=/(?:墙根|洞口|门口|路口|谷口|沟口|村口|镇口|城门|崖根|树下|屋里|屋内|院里|院内|旁|旁边|边缘|北缘|南缘|东缘|西缘)$/u;
const PLACE_SUFFIX_RE=/(?:港|溪|潭|峰|崖|坡|坳|洼|滩|关|隘|堡|宫|殿|寺|观|塔|洞|窟|坊|街|巷|桥|渡|码头|营地|遗迹|秘境|禁地|段|缘)$/u;
const DIR_PREFIX_RE=/^(?:东|西|南|北|东北|西北|东南|西南|上|下|内|外|前|后|左|右)(?:侧|段|部|缘)?/u;
const SURNAME_1=new Set([...'赵钱孙李周吴郑王冯陈沈韩杨朱秦许何吕张曹金魏姜谢范彭马袁史唐薛雷罗宋熊董梁杜郭林钟徐高夏蔡田胡霍卢莫丁邓洪左石崔程陆段刘龙叶白乔谭温廖文']);
const SURNAME_2=['欧阳','司马','上官','诸葛','夏侯','皇甫','尉迟','公孙','慕容','令狐','宇文','长孙','司徒','司空'];
const ACTIONS=['低声道','轻声道','沉声道','插了一句','摆了摆手','摇了摇头','点了点头','转过身','转身','回头','抬头','低头','点头','摇头','皱眉','开口','伸手','抬手','摆手','扶起','扶','拉','推','递','接','拍','说','道','问','答','喊','叫','笑','哭','看','瞥','盯','望','站','坐','蹲','跪','躺','靠','走来','过来','赶到','来到','进来','出现','凑近','靠近','上前','跟着','跟在','走','跑','回','进','出'];
const ADVERBS=['正','正在','又','再','便','却','也','先','后','忽然','突然','已经','还','仍','就','才'];
const REMOTE_RE=/(?:准备|打算|计划|想要|要去|前往|赶往|去找|寻找|拜访|探望|看望|听说|听闻|据说|提起|谈起|想到|想起|回忆|打听|询问)/u;
const RELATION_RE=/^(?:你|我|他|她|咱)(?:爷爷|奶奶|外公|外婆|父亲|母亲|爹|娘|爸爸|妈妈|哥哥|姐姐|弟弟|妹妹|叔叔|伯伯|婶婶|姑姑|姨妈|舅舅|师父|师傅)/u;
const FAMILIAR_RE=/^(?:老|小|阿)[\p{Script=Han}]/u;
const uniq=a=>[...new Set((a||[]).filter(Boolean))];
function stripTimestampPrefix(value){let s=String(value||'').trim();for(let i=0;i<2;i++){const n=s.replace(TIME_PREFIX_RE,'').replace(BARE_TIME_PREFIX_RE,'').trim();if(n===s)break;s=n;}return s;}
function stripOuterBrackets(s){return String(s||'').trim().replace(/^[【[]\s*/u,'').replace(/\s*[】\]]$/u,'').trim();}
function stripParentheticalQualifier(s){const v=String(s||'').trim(),i=v.search(/[（(]/u);return i>=2?v.slice(0,i).trim():v;}
function stripDanglingCloser(s){let v=String(s||'').trim();while(/[）)]$/u.test(v)){const o=(v.match(/[（(]/gu)||[]).length,c=(v.match(/[）)]/gu)||[]).length;if(c<=o)break;v=v.slice(0,-1).trim();}return v;}
function normalizeLocationSegment(s){return stripDanglingCloser(stripParentheticalQualifier(stripTimestampPrefix(stripOuterBrackets(s)))).replace(/^[,，;；:：\s]+|[,，;；:：\s]+$/gu,'').trim();}
function normalizeLocationParts(raw){const src=stripTimestampPrefix(stripOuterBrackets(raw));if(!src)return[];return src.split(/\s*[·•›>→/／]+\s*/u).map(normalizeLocationSegment).filter(x=>x.length>=2&&x.length<=40&&!/^\d{1,2}:\d{2}(?::\d{2})?$/u.test(x));}
function parseHeaderLocation(text){const lines=String(text||'').split(/\n/).slice(0,10).map(x=>x.trim()).filter(Boolean);for(const line of lines){const m=line.match(/[【[]\s*([^】\]\n]+)\s*[】\]]/u);if(m&&(TIME_PREFIX_RE.test(m[1])||BARE_TIME_PREFIX_RE.test(m[1]))){const p=normalizeLocationParts(m[1]);if(p.length)return p;}}for(const line of lines){if(TIME_PREFIX_RE.test(line)||BARE_TIME_PREFIX_RE.test(line)){const p=normalizeLocationParts(line);if(p.length)return p;}}return null;}
function placeKind(name){const s=normalizeLocationSegment(name);if(LOCAL_DETAIL_SUFFIX_RE.test(s))return'local-detail';if(ROUTE_SUFFIX_RE.test(s))return'route';if(/(?:段|缘)$/u.test(s))return'segment';if(CONTAINER_SUFFIX_RE.test(s))return'container';if(PLACE_SUFFIX_RE.test(s))return'place';return'unknown';}
function parentScore(child,parent){const c=normalizeLocationSegment(child),p=normalizeLocationSegment(parent);if(!c||!p||c===p||c.length<=p.length||!c.startsWith(p))return 0;const ck=placeKind(c),pk=placeKind(p),tail=c.slice(p.length);let score=40+p.length;if(DIR_PREFIX_RE.test(tail))score+=12;if(pk==='container'&&['route','segment','local-detail','place'].includes(ck))score+=18;if(pk==='route'&&['segment','local-detail'].includes(ck))score+=22;return score;}
function surnameLengthAt(src,i){for(const s of SURNAME_2)if(src.startsWith(s,i))return 2;return SURNAME_1.has(src[i])?1:0;}
function actionAt(rest){let r=String(rest||'').replace(/^\s+/u,'');for(const a of ADVERBS)if(r.startsWith(a)){r=r.slice(a.length).replace(/^\s+/u,'');break;}for(const a of ACTIONS)if(r.startsWith(a))return a;return null;}
function predicateAfter(rest){const r=String(rest||'');if(actionAt(r))return true;const lead=r.match(/^\s*在/u);if(!lead)return false;const start=lead[0].length;for(let k=start+1;k<=Math.min(r.length,start+12);k++){if(/[，。！？!?；;：:]/u.test(r[k-1]||''))break;if(actionAt(r.slice(k)))return true;}return false;}
function personNameAt(src,i,requireAction=true){const rel=src.slice(i).match(RELATION_RE);if(rel){const n=rel[0];if(!requireAction||predicateAfter(src.slice(i+n.length)))return n;}const fam=src.slice(i).match(FAMILIAR_RE);if(fam){const n=fam[0];if(!requireAction||predicateAfter(src.slice(i+n.length)))return n;}const sl=surnameLengthAt(src,i);if(!sl)return null;for(let total=sl+1;total<=sl+2;total++){const n=src.slice(i,i+total);if(!/^[\p{Script=Han}]{2,4}$/u.test(n))continue;if(!requireAction||predicateAfter(src.slice(i+total)))return n;}return null;}
function nearRemote(src,start,end){return REMOTE_RE.test(src.slice(Math.max(0,start-14),Math.min(src.length,end+14)));}
function extractPeople(text,known=[]){const src=String(text||''),out=[];const add=(n,s,e)=>{if(n&&!nearRemote(src,s,e)&&!out.includes(n))out.push(n);};for(let i=0;i<src.length;i++){if(i>0&&!/[。！？!?；;\n：:“”「」『』，,]/u.test(src[i-1]))continue;const n=personNameAt(src,i,true);if(n)add(n,i,i+n.length);}const cue=/(?:让|叫|请|扶|拉|推|找|问|看向|望向|对着|跟着|跟|和|与)/gu;for(const m of src.matchAll(cue)){let i=m.index+m[0].length;while(/\s/u.test(src[i]||''))i++;const n=personNameAt(src,i,false);if(n)add(n,i,i+n.length);}for(let i=0;i<src.length;i++){const a=personNameAt(src,i,false);if(!a)continue;let j=i+a.length;const sep=src.slice(j).match(/^\s*(?:和|与|跟)\s*/u);if(!sep)continue;j+=sep[0].length;const b=personNameAt(src,j,false);if(!b)continue;if(predicateAfter(src.slice(j+b.length))){add(a,i,i+a.length);add(b,j,j+b.length);}}for(const k of known){const n=String(k||'').trim();if(!n)continue;let idx=src.indexOf(n);while(idx>=0){const before=src.slice(Math.max(0,idx-3),idx),after=src.slice(idx+n.length);if(predicateAfter(after)||/(?:让|叫|请|扶|拉|推|找|问|看向|望向|对着|跟着|跟|和|与)\s*$/u.test(before))add(n,idx,idx+n.length);idx=src.indexOf(n,idx+1);}}return uniq(out).slice(0,16);}
const api={normalizeLocationSegment,normalizeLocationParts,parseHeaderLocation,placeKind,parentScore,extractPeople,actionAt,personNameAt,predicateAfter};globalThis.MapNEntityCore=api;export {normalizeLocationSegment,normalizeLocationParts,parseHeaderLocation,placeKind,parentScore,extractPeople,actionAt,personNameAt,predicateAfter};
