// Map-N scene scanner v2.0.2
// Responsibility: learn canonical location chains from structured scene headers. No person parsing here.
const wait=ms=>new Promise(r=>setTimeout(r,ms)),ROOT='世界舆图',MEMORY_VERSION=5;
const uniq=a=>[...new Set((a||[]).map(x=>String(x).trim()).filter(Boolean))];
const storeKey=i=>`${i.memoryKey}:scene-v2`;
const empty=()=>({version:MEMORY_VERSION,learnedLocations:{}});
function load(i){try{const r=JSON.parse(localStorage.getItem(storeKey(i))||'null')||{};return{...empty(),...r,learnedLocations:r.learnedLocations||{}}}catch{return empty()}}
function save(i){try{localStorage.setItem(storeKey(i),JSON.stringify(i.__mapNSceneStore||empty()))}catch(e){console.warn('[Map-N] 场景地点保存失败',e)}}
function recentRange(chat){const a=Array.isArray(chat)?chat:[],api=globalThis.MapNHistoryWindow;return api?.range?api.range(a):{start:0,end:a.length};}
function canonicalPath(core,value){if(!value||value===ROOT)return value;const parts=String(value).split('／').flatMap(x=>core.normalizeLocationParts(x));return parts.length?parts.join('／'):core.normalizeLocationSegment(value);}
function migrate(i,core){const s=i.__mapNSceneStore||=load(i),next={};let changed=s.version!==MEMORY_VERSION;for(const rec of Object.values(s.learnedLocations||{})){const parts=String(rec?.id||'').split('／').flatMap(x=>core.normalizeLocationParts(x));let label=core.normalizeLocationSegment(rec?.label||parts.at(-1)||'');if(!label)continue;if(!parts.length)parts.push(label);const id=parts.join('／'),parent=parts.length>1?parts.slice(0,-1).join('／'):ROOT,aliases=uniq([label,...(rec?.aliases||[]).map(core.normalizeLocationSegment)]);if(id!==rec?.id||parent!==(rec?.parent||ROOT)||label!==rec?.label)changed=true;next[id]={id,label,parent,aliases,learned:true,source:'scene-header'};}s.learnedLocations=next;s.version=MEMORY_VERSION;if(changed){if(i.discovered instanceof Set)i.discovered=new Set([...i.discovered].map(x=>x===ROOT?ROOT:canonicalPath(core,x)).filter(Boolean));if(i.currentPos)i.currentPos=canonicalPath(core,i.currentPos);if(Array.isArray(i.path))i.path=i.path.map(x=>x===ROOT?ROOT:canonicalPath(core,x)).filter(Boolean);save(i);}return changed;}
function ensure(i,core,parts){const s=i.__mapNSceneStore||=load(i);let parent=ROOT,changed=false;for(let n=0;n<parts.length;n++){const id=parts.slice(0,n+1).join('／'),label=parts[n],existing=s.learnedLocations[id];if(!existing){s.learnedLocations[id]={id,label,parent,aliases:[label],learned:true,source:'scene-header'};changed=true;}else{const aliases=uniq([...(existing.aliases||[]),label]);if(existing.id!==id||existing.label!==label||existing.parent!==parent||aliases.length!==(existing.aliases||[]).length){existing.id=id;existing.label=label;existing.parent=parent;existing.aliases=aliases;existing.learned=true;existing.source='scene-header';changed=true;}}parent=id;}if(changed)save(i);return parent;}
function merge(i,core){migrate(i,core);for(const r of Object.values(i.__mapNSceneStore?.learnedLocations||{})){if(!i.nodeMap[r.id])i.nodeMap[r.id]={id:r.id,displayName:r.label,aliases:[...r.aliases],content:'剧情场景头确认的地点',type:'location',children:[],parent:r.parent,isWater:/海|河|湖|江|溪|潭|湾|岸|滩/u.test(r.label),isMountain:/山|峰|岭|崖|峪|谷/u.test(r.label),learned:true,source:'scene-header'};const n=i.nodeMap[r.id];n.displayName=r.label;n.parent=r.parent;n.learned=true;n.source='scene-header';n.aliases=uniq([...(n.aliases||[]),...r.aliases,r.label]);for(const a of n.aliases)if(!i.alias.has(a))i.alias.set(a,r.id);i.discovered.add(r.id);}for(const r of Object.values(i.__mapNSceneStore?.learnedLocations||{})){if(r.parent===ROOT){i.root.children||=[];if(!i.root.children.includes(r.id))i.root.children.push(r.id);}else if(i.nodeMap[r.parent]){i.nodeMap[r.parent].children||=[];if(!i.nodeMap[r.parent].children.includes(r.id))i.nodeMap[r.parent].children.push(r.id);}}}
function learn(i,core,parts,setCurrent=true){const clean=(parts||[]).map(core.normalizeLocationSegment).filter(Boolean);if(!clean.length)return null;const leaf=ensure(i,core,clean);merge(i,core);if(setCurrent){i.currentPos=leaf;i.path=i.pathTo(leaf);}i.save?.();return leaf;}
async function install(){for(let n=0;n<160&&(!window.MapNInstance||!globalThis.MapNEntityCore);n++)await wait(50);const i=window.MapNInstance,core=globalThis.MapNEntityCore;if(!i||!core||i.__sceneScanner202)return;i.__sceneScanner202=true;i.__mapNSceneStore=load(i);migrate(i,core);const oldBuild=i.build.bind(i);i.build=function(entries){oldBuild(entries);merge(this,core);};const oldProcess=i.process.bind(i);i.process=function(text,isUser=false){oldProcess(text,isUser);if(!isUser&&text){const parts=core.parseHeaderLocation(text);if(parts?.length)learn(this,core,parts,true);}if(this.container?.classList.contains('open'))this.render?.();};merge(i,core);const chat=i.ctx?.chat||[],r=recentRange(chat);for(let n=r.end-1;n>=r.start;n--){const m=chat[n];if(m?.mes&&!m.is_user){const p=core.parseHeaderLocation(m.mes);if(p?.length){learn(i,core,p,true);break;}}}i.render?.();console.log('[Map-N] scene scanner v2.0.2 installed');}
install();
