// Map-N scene scanner v2.1.1
// Responsibility: learn canonical location chains from structured scene headers. No person parsing here.
// Scene-header locations keep message provenance so recent swipe/update/delete can roll back only affected learned nodes.
const wait=ms=>new Promise(r=>setTimeout(r,ms)),ROOT='世界舆图',MEMORY_VERSION=6;
const uniq=a=>[...new Set((a||[]).map(x=>String(x).trim()).filter(Boolean))];
const storeKey=i=>`${i.memoryKey}:scene-v2`;
const empty=()=>({version:MEMORY_VERSION,learnedLocations:{}});
function load(i){try{const r=JSON.parse(localStorage.getItem(storeKey(i))||'null')||{};return{...empty(),...r,learnedLocations:r.learnedLocations||{}}}catch{return empty()}}
function write(i){try{localStorage.setItem(storeKey(i),JSON.stringify(i.__mapNSceneStore||empty()))}catch(e){console.warn('[Map-N] 场景地点保存失败',e)}}
function save(i){if((i.__mapNBatchDepth||0)>0){i.__mapNSceneSaveDirty=true;return;}write(i);}
function recentRange(chat){const a=Array.isArray(chat)?chat:[],api=globalThis.MapNHistoryWindow;return api?.range?api.range(a):{start:0,end:a.length};}
function hashText(s){let h=2166136261;for(const ch of String(s||'')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function sourceKey(index,text){return Number.isInteger(index)&&index>=0?`${index}:${hashText(text)}`:null}
function inferSourceIndex(i,text){const forced=Number(i.__mapNProcessingMessageIndex);if(Number.isInteger(forced)&&forced>=0)return forced;const chat=i.ctx?.chat||[];for(let n=chat.length-1;n>=0;n--)if(String(chat[n]?.mes||'')===String(text||''))return n;return -1}
function canonicalPath(core,value){if(!value||value===ROOT)return value;const parts=String(value).split('／').flatMap(x=>core.normalizeLocationParts(x));return parts.length?parts.join('／'):core.normalizeLocationSegment(value);}
function migrate(i,core){const s=i.__mapNSceneStore||=load(i),next={};let changed=s.version!==MEMORY_VERSION;for(const rec of Object.values(s.learnedLocations||{})){const parts=String(rec?.id||'').split('／').flatMap(x=>core.normalizeLocationParts(x));let label=core.normalizeLocationSegment(rec?.label||parts.at(-1)||'');if(!label)continue;if(!parts.length)parts.push(label);const id=parts.join('／'),parent=parts.length>1?parts.slice(0,-1).join('／'):ROOT,aliases=uniq([label,...(rec?.aliases||[]).map(core.normalizeLocationSegment)]),sources=uniq(rec?.sources||[]);if(id!==rec?.id||parent!==(rec?.parent||ROOT)||label!==rec?.label||s.version!==MEMORY_VERSION)changed=true;next[id]={id,label,parent,aliases,sources,learned:true,source:'scene-header'};}s.learnedLocations=next;s.version=MEMORY_VERSION;if(changed){if(i.discovered instanceof Set)i.discovered=new Set([...i.discovered].map(x=>x===ROOT?ROOT:canonicalPath(core,x)).filter(Boolean));if(i.currentPos)i.currentPos=canonicalPath(core,i.currentPos);if(Array.isArray(i.path))i.path=i.path.map(x=>x===ROOT?ROOT:canonicalPath(core,x)).filter(Boolean);save(i);}return changed;}
function ensure(i,core,parts,src=null){const s=i.__mapNSceneStore||=load(i);if(s.version!==MEMORY_VERSION)migrate(i,core);let parent=ROOT,changed=false;const touched=[];for(let n=0;n<parts.length;n++){const id=parts.slice(0,n+1).join('／'),label=parts[n],existing=s.learnedLocations[id];if(!existing){s.learnedLocations[id]={id,label,parent,aliases:[label],sources:src?[src]:[],learned:true,source:'scene-header'};changed=true;}else{const aliases=uniq([...(existing.aliases||[]),label]),sources=uniq([...(existing.sources||[]),...(src?[src]:[])]);if(existing.id!==id||existing.label!==label||existing.parent!==parent||aliases.length!==(existing.aliases||[]).length||sources.length!==(existing.sources||[]).length){existing.id=id;existing.label=label;existing.parent=parent;existing.aliases=aliases;existing.sources=sources;existing.learned=true;existing.source='scene-header';changed=true;}}touched.push(id);parent=id;}if(changed)save(i);return{leaf:parent,touched,changed};}
function mergeRecord(i,r){if(!r)return;const aliases=uniq([...(r.aliases||[]),r.label]),existing=i.nodeMap[r.id];if(!existing){i.nodeMap[r.id]={id:r.id,displayName:r.label,aliases:[...aliases],content:'剧情场景头确认的地点',type:'location',children:[],parent:r.parent,isWater:/海|河|湖|江|溪|潭|湾|岸|滩/u.test(r.label),isMountain:/山|峰|岭|崖|峪|谷/u.test(r.label),learned:true,source:'scene-header'};}const n=i.nodeMap[r.id];const sceneOwned=n.source==='scene-header'&&n.learned===true;if(sceneOwned){n.displayName=r.label;n.parent=r.parent;n.learned=true;n.source='scene-header';}n.aliases=uniq([...(n.aliases||[]),...aliases]);for(const a of n.aliases)if(!i.alias.has(a))i.alias.set(a,r.id);i.discovered.add(r.id);if(sceneOwned){if(r.parent===ROOT){i.root.children||=[];if(!i.root.children.includes(r.id))i.root.children.push(r.id);}else if(i.nodeMap[r.parent]){i.nodeMap[r.parent].children||=[];if(!i.nodeMap[r.parent].children.includes(r.id))i.nodeMap[r.parent].children.push(r.id);}}}
function mergeAll(i,core){migrate(i,core);for(const r of Object.values(i.__mapNSceneStore?.learnedLocations||{}))mergeRecord(i,r);}
function learn(i,core,parts,setCurrent=true,sourceIndex=null,sourceText=''){const clean=(parts||[]).map(core.normalizeLocationSegment).filter(Boolean);if(!clean.length)return null;const idx=Number.isInteger(sourceIndex)?sourceIndex:inferSourceIndex(i,sourceText),src=sourceKey(idx,sourceText);const{leaf,touched}=ensure(i,core,clean,src);const s=i.__mapNSceneStore;for(const id of touched)mergeRecord(i,s?.learnedLocations?.[id]);if(setCurrent){i.currentPos=leaf;i.path=i.pathTo(leaf);}i.save?.();return leaf;}
function detachNode(i,id){const n=i.nodeMap?.[id];if(!n||n.source!=='scene-header'||n.learned!==true)return;delete i.nodeMap[id];for(const [a,target] of [...(i.alias?.entries?.()||[])])if(target===id)i.alias.delete(a);i.discovered?.delete?.(id);if(i.currentPos===id)i.currentPos=null;if(Array.isArray(i.path)&&i.path.includes(id))i.path=[ROOT];}
function reconcileRecent(i,start,end,chat){const s=i.__mapNSceneStore||=load(i);const valid=new Set();for(let n=start;n<end;n++){const m=chat?.[n];if(m?.mes&&!m.is_user)valid.add(sourceKey(n,String(m.mes)));}let changed=false;for(const [id,rec] of Object.entries(s.learnedLocations||{})){const sources=uniq(rec?.sources||[]);if(!sources.length)continue;const kept=sources.filter(k=>{const idx=Number(String(k).split(':',1)[0]);return !Number.isInteger(idx)||idx<start||valid.has(k)});if(kept.length!==sources.length){rec.sources=kept;changed=true;}if(!kept.length){delete s.learnedLocations[id];detachNode(i,id);changed=true;}}if(changed){i.__mapNHierarchyGraphSig=null;save(i);}return changed;}
async function install(){for(let n=0;n<160&&(!window.MapNInstance||!globalThis.MapNEntityCore);n++)await wait(50);const i=window.MapNInstance,core=globalThis.MapNEntityCore;if(!i||!core||i.__sceneScanner211)return;i.__sceneScanner211=true;i.__mapNSceneStore=load(i);migrate(i,core);const priorFlush=i.__mapNFlushBatch?.bind(i);i.__mapNFlushBatch=function(){priorFlush?.();if(this.__mapNSceneSaveDirty){this.__mapNSceneSaveDirty=false;write(this);}};const oldBuild=i.build.bind(i);i.build=function(entries){oldBuild(entries);mergeAll(this,core);};const oldProcess=i.process.bind(i);i.process=function(text,isUser=false){oldProcess(text,isUser);if(!isUser&&text){const parts=core.parseHeaderLocation(text);if(parts?.length)learn(this,core,parts,true,null,String(text));}if(this.container?.classList.contains('open'))this.render?.();};mergeAll(i,core);const chat=i.ctx?.chat||[],r=recentRange(chat);for(let n=r.end-1;n>=r.start;n--){const m=chat[n];if(m?.mes&&!m.is_user){const p=core.parseHeaderLocation(m.mes);if(p?.length){learn(i,core,p,true,n,String(m.mes));break;}}}globalThis.MapNSceneScanner={reconcileRecent:(inst,start,end,all)=>reconcileRecent(inst,start,end,all)};const es=i.ctx?.eventSource,et=i.ctx?.eventTypes||i.ctx?.event_types;if(es&&et){const onMutation=()=>setTimeout(()=>{const fresh=window.SillyTavern?.getContext?.();if(fresh)i.ctx=fresh;const all=i.ctx?.chat||[],rr=recentRange(all);if(reconcileRecent(i,rr.start,rr.end,all))i.render?.();},80);['MESSAGE_SWIPED','MESSAGE_UPDATED','MESSAGE_DELETED'].forEach(k=>{if(et[k])es.on(et[k],onMutation)});}i.render?.();console.log('[Map-N] scene scanner v2.1.1 installed');}
install();
