// Map-N timeline state v1.3.0
// SillyTavern chat + swipe is the only timeline. Replay explicitly applies deterministic scene-header derivation.
const ROOT='世界舆图',STATE_KEY='map_n_state',STATE_VERSION=1,ENGINE_VERSION=4,DEFAULT_CHECKPOINT_INTERVAL=25;
const wait=ms=>new Promise(r=>setTimeout(r,ms)),clone=v=>v==null?v:JSON.parse(JSON.stringify(v)),uniq=a=>[...new Set((a||[]).filter(Boolean))];
function hashString(value){const s=String(value||'');let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function checkpointInterval(){const n=Number(globalThis.MapNCheckpointInterval);return Number.isFinite(n)&&n>=5?Math.floor(n):DEFAULT_CHECKPOINT_INTERVAL}
function refreshContext(inst){const fresh=window.SillyTavern?.getContext?.();if(fresh)inst.ctx=fresh;try{inst.memoryKey=inst.scopeKey()}catch{}return inst.ctx}
function derivationReady(inst){return !!(inst&&globalThis.MapNEntityCore&&globalThis.MapNSceneScanner?.applyMessage&&inst.__strictEntity201&&inst.__presence202)}
async function waitForDerivation(inst,timeout=12000){const start=Date.now();while(Date.now()-start<timeout){if(derivationReady(inst))return true;await wait(50)}console.warn('[Map-N timeline] derivation chain not ready; replay postponed');return false}
function hasSwipeSlot(m){const sid=Number(m?.swipe_id);return !!m&&!m.is_user&&Number.isInteger(sid)&&sid>=0&&Array.isArray(m.swipe_info)&&!!m.swipe_info[sid]}
function currentSwipeExtra(m,create=false){if(!hasSwipeSlot(m))return null;const info=m.swipe_info[Number(m.swipe_id)];if(!info.extra&&create)info.extra={};return info.extra||null}
function readRecord(m){return hasSwipeSlot(m)?currentSwipeExtra(m,false)?.[STATE_KEY]||null:m?.extra?.[STATE_KEY]||null}
function writeRecord(m,record){if(!m||m.is_user)return;const value=clone({...record,engineVersion:ENGINE_VERSION});if(hasSwipeSlot(m)){currentSwipeExtra(m,true)[STATE_KEY]=value;return}if(!m.extra||typeof m.extra!=='object')m.extra={};m.extra[STATE_KEY]=value}
function removeRecords(m){if(!m)return;if(m.extra&&typeof m.extra==='object')delete m.extra[STATE_KEY];if(Array.isArray(m.swipe_info))for(const info of m.swipe_info)if(info?.extra&&typeof info.extra==='object')delete info.extra[STATE_KEY]}
function recordValid(r,h=null){return !!r&&r.version===STATE_VERSION&&r.engineVersion===ENGINE_VERSION&&(h==null||r.chainHash===h)}
function chatHashes(chat){const out=[];let chain=`mapn-state-${STATE_VERSION}-engine-${ENGINE_VERSION}`;for(let i=0;i<chat.length;i++){const m=chat[i]||{},part=`${i}|${m.is_user?'u':'a'}|${Number(m.swipe_id??0)}|${String(m.mes||'')}`;chain=hashString(`${chain}\n${part}`);out.push(chain)}return out}
function snapshot(i){return{discovered:uniq([ROOT,...(i.discovered instanceof Set?[...i.discovered]:[])]),encountered:uniq(i.encountered instanceof Set?[...i.encountered]:[]),currentPos:i.currentPos||null,currentChars:uniq(i.currentChars||[]),learnedLocations:clone(i.__mapNSceneStore?.learnedLocations||{})}}
function emptySnapshot(){return{discovered:[ROOT],encountered:[],currentPos:null,currentChars:[],learnedLocations:{}}}
function normalizeSnapshot(state){const s=clone(state)||emptySnapshot();return{discovered:uniq([ROOT,...(s.discovered||[])]),encountered:uniq(s.encountered||[]),currentPos:s.currentPos||null,currentChars:uniq(s.currentChars||[]),learnedLocations:clone(s.learnedLocations||{})}}
function deltaBetween(a,b){const ad=new Set(a.discovered||[]),ae=new Set(a.encountered||[]),learned={};for(const[id,rec]of Object.entries(b.learnedLocations||{}))if(JSON.stringify(a.learnedLocations?.[id]||null)!==JSON.stringify(rec))learned[id]=clone(rec);return{discoveredAdded:(b.discovered||[]).filter(x=>!ad.has(x)),encounteredAdded:(b.encountered||[]).filter(x=>!ae.has(x)),learnedUpserts:learned,currentPos:b.currentPos||null,currentChars:uniq(b.currentChars||[])}}
function applyDelta(base,r){const n=normalizeSnapshot(base);n.discovered=uniq([ROOT,...n.discovered,...(r.discoveredAdded||[])]);n.encountered=uniq([...n.encountered,...(r.encounteredAdded||[])]);for(const[id,rec]of Object.entries(r.learnedUpserts||{}))n.learnedLocations[id]=clone(rec);n.currentPos=r.currentPos||null;n.currentChars=uniq(r.currentChars||[]);return n}
function recordState(r,base){if(!recordValid(r))return null;if(r.kind==='checkpoint'&&r.snapshot)return normalizeSnapshot(r.snapshot);if(r.kind==='delta')return applyDelta(base,r);return null}
function validBrowsePath(i,p){return Array.isArray(p)&&p.length&&(!i.validPath||i.validPath(p))}
function applySnapshot(i,state,{preserveBrowse=true,browsePath=null}={}){const s=normalizeSnapshot(state),browse=Array.isArray(browsePath)?[...browsePath]:(preserveBrowse&&Array.isArray(i.path)?[...i.path]:[ROOT]);i.__mapNSceneStore={version:5,learnedLocations:clone(s.learnedLocations)};i.__mapNPresenceState={version:3,current:uniq(s.currentChars),lastLocation:s.currentPos};i.discovered=new Set([ROOT]);i.encountered=new Set(s.encountered);i.currentPos=null;i.currentChars=[];try{if(Array.isArray(i.entries))i.build(i.entries)}catch(e){console.warn('[Map-N timeline] runtime graph rebuild failed',e)}i.discovered=new Set(s.discovered);i.encountered=new Set(s.encountered);i.currentPos=s.currentPos;i.currentChars=uniq(s.currentChars);if(validBrowsePath(i,browse))i.path=browse;else if(i.currentPos&&i.pathTo)i.path=i.pathTo(i.currentPos);else i.path=[ROOT];try{localStorage.setItem(`${i.memoryKey}:scene-v2`,JSON.stringify(i.__mapNSceneStore))}catch{}try{localStorage.setItem(`${i.memoryKey}:presence-v1`,JSON.stringify(i.__mapNPresenceState))}catch{}try{i.save?.()}catch{}}
function findLastAssistant(chat,limit=chat.length-1){for(let i=Math.min(limit,chat.length-1);i>=0;i--)if(chat[i]&&!chat[i].is_user)return i;return-1}
function assistantOrdinalAt(chat,index){let n=-1;for(let i=0;i<=index&&i<chat.length;i++)if(chat[i]&&!chat[i].is_user)n++;return n}
function findValidCheckpoint(chat,hashes,before){for(let i=Math.min(before,chat.length-1);i>=0;i--){const m=chat[i];if(!m||m.is_user)continue;const r=readRecord(m);if(recordValid(r,hashes[i])&&r.kind==='checkpoint'&&r.snapshot)return{index:i,state:normalizeSnapshot(r.snapshot)}}return{index:-1,state:emptySnapshot()}}
function restoreRecordedState(chat,hashes,target){if(target<0)return emptySnapshot();const cp=findValidCheckpoint(chat,hashes,target);let state=cp.state;for(let i=cp.index+1;i<=target;i++){const m=chat[i];if(!m||m.is_user)continue;const r=readRecord(m);if(!recordValid(r,hashes[i]))return null;state=recordState(r,state);if(!state)return null}return state}
async function persistChat(i){try{const result=i.ctx?.saveChat?.();if(result?.then)await result}catch(e){console.warn('[Map-N timeline] saveChat failed',e)}}
function batch(i,fn){return globalThis.MapNHistoryWindow?.batch?globalThis.MapNHistoryWindow.batch(i,fn):fn()}
function deriveMessage(i,text){i.process(String(text),false);const scene=globalThis.MapNSceneScanner?.applyMessage?.(i,String(text),{setCurrent:true});if(scene)console.debug('[Map-N timeline] scene',scene.leaf);return scene}
let synchronizing=false,queued=false,queuedReason='event';
async function synchronize(reason='event',{forceWorld=false}={}){const i=window.MapNInstance;if(!i)return null;if(!derivationReady(i)&&!await waitForDerivation(i))return null;if(synchronizing){queued=true;queuedReason=reason;return null}synchronizing=true;try{refreshContext(i);const browse=Array.isArray(i.path)?[...i.path]:[ROOT];if(forceWorld)try{await i.prime(true)}catch(e){console.warn('[Map-N timeline] world refresh failed',e)}const chat=Array.isArray(i.ctx?.chat)?i.ctx.chat:[],hashes=chatHashes(chat),lastAI=findLastAssistant(chat);if(lastAI<0){applySnapshot(i,emptySnapshot(),{browsePath:browse});i.render?.();return emptySnapshot()}let firstInvalid=-1;for(let n=0;n<=lastAI;n++){const m=chat[n];if(!m||m.is_user)continue;if(!recordValid(readRecord(m),hashes[n])){firstInvalid=n;break}}if(firstInvalid<0){const restored=restoreRecordedState(chat,hashes,lastAI);if(restored){applySnapshot(i,restored,{browsePath:browse});i.render?.();return restored}firstInvalid=0}const cp=findValidCheckpoint(chat,hashes,firstInvalid-1);applySnapshot(i,cp.state,{browsePath:browse});let state=clone(cp.state),ordinal=assistantOrdinalAt(chat,cp.index);const interval=checkpointInterval();batch(i,()=>{for(let n=cp.index+1;n<=lastAI;n++){const m=chat[n];if(!m||m.is_user||!m.mes)continue;ordinal++;const before=clone(state);deriveMessage(i,m.mes);state=snapshot(i);const checkpoint=ordinal===0||ordinal%interval===0;writeRecord(m,checkpoint?{version:STATE_VERSION,kind:'checkpoint',chainHash:hashes[n],snapshot:clone(state)}:{version:STATE_VERSION,kind:'delta',chainHash:hashes[n],...deltaBetween(before,state)})}});applySnapshot(i,state,{browsePath:browse});await persistChat(i);i.render?.();console.log(`[Map-N timeline] synchronized (${reason}) from ${cp.index+1} to ${lastAI}; current=${state.currentPos||'none'}; learned=${Object.keys(state.learnedLocations||{}).length}`);return state}finally{synchronizing=false;if(queued){const r=queuedReason;queued=false;queuedReason='event';setTimeout(()=>synchronize(r),0)}}}
async function commitCurrentCheckpoint(reason='manual',stateOverride=null){const i=window.MapNInstance;if(!i)return false;if(!derivationReady(i)&&!await waitForDerivation(i))return false;refreshContext(i);const chat=Array.isArray(i.ctx?.chat)?i.ctx.chat:[],lastAI=findLastAssistant(chat);if(lastAI<0)return false;const hashes=chatHashes(chat),state=normalizeSnapshot(stateOverride||snapshot(i));applySnapshot(i,state);writeRecord(chat[lastAI],{version:STATE_VERSION,kind:'checkpoint',chainHash:hashes[lastAI],snapshot:state,reason});await persistChat(i);return true}
async function clearCurrentChat(){const i=window.MapNInstance;if(!i)return;refreshContext(i);const chat=Array.isArray(i.ctx?.chat)?i.ctx.chat:[];for(const m of chat)removeRecords(m);try{localStorage.removeItem(i.memoryKey);localStorage.removeItem(`${i.memoryKey}:scene-v2`);localStorage.removeItem(`${i.memoryKey}:presence-v1`)}catch{}i.__mapNSceneStore={version:5,learnedLocations:{}};applySnapshot(i,emptySnapshot(),{preserveBrowse:false});await persistChat(i);i.render?.()}
function bindEvents(i){const es=i.ctx?.eventSource,et=i.ctx?.eventTypes||i.ctx?.event_types;if(!es||!et)return;let timer=null;const queue=reason=>{clearTimeout(timer);timer=setTimeout(()=>synchronize(reason),90)};['MESSAGE_RECEIVED','MESSAGE_SWIPED','MESSAGE_UPDATED','MESSAGE_EDITED','MESSAGE_DELETED'].forEach(k=>{if(et[k])es.on(et[k],()=>queue(k))});if(et.WORLDINFO_ENTRIES_LOADED)es.on(et.WORLDINFO_ENTRIES_LOADED,()=>queue('WORLDINFO_ENTRIES_LOADED'))}
async function install(){for(let n=0;n<180&&!window.MapNInstance;n++)await wait(50);const i=window.MapNInstance;if(!i||i.__mapNTimelineState130)return;if(!await waitForDerivation(i))return;i.__mapNTimelineState130=true;globalThis.MapNCheckpointInterval=globalThis.MapNCheckpointInterval||DEFAULT_CHECKPOINT_INTERVAL;globalThis.MapNTimeline={synchronize,commitCurrentCheckpoint,clearCurrentChat,readRecord,writeRecord,snapshot,normalizeSnapshot,stateVersion:STATE_VERSION,engineVersion:ENGINE_VERSION};bindEvents(i);await synchronize('startup');console.log(`[Map-N] timeline state v1.3.0 installed; engine ${ENGINE_VERSION}; checkpoint interval ${checkpointInterval()} assistant messages`)}
install();
export{synchronize,commitCurrentCheckpoint,clearCurrentChat,readRecord,writeRecord,snapshot,normalizeSnapshot};
